### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by mbussieck** [etsap-TIMES/TIMES_model#1]
I cloned the repo, unpacked the zip archive, and started gams with `gams maindrv.mod` as well `gams maindrv.mod r=_times` in both cases I get

```
--- maindrv.mod(23) 2 Mb
--- . setglobs.gms(59) 2 Mb
--- maindrv.mod(43) 2 Mb
***
*** Abort "*** ERRORS IN INPUT DATA/COMPILE ***"
--- maindrv.mod(43) 3 Mb 2 Errors
*** Status: Compilation error(s)
--- Job maindrv.mod Stop 01/21/20 08:17:59 elapsed 0:00:00.018
```

The first error is about a set `j`:

```
 572  SET SOLVESTAT(J) /
****                $120
```
I did not find a short description how to get the model to run with GAMS. Can someone point me to something like a (quick start) guide.

BTW, for git and pull requests it might be much better to have the source files directly in the repo rather than the source files in a zip archive.

**Comment by Antti-L** [comment]
Thanks for the comment.  
Yes, as you have noticed, TIMES cannot be run with GAMS using maindrv.mod as the "main program".  The user shells normally take care of creating a **driver file** (we call it a RUN file) for the GAMS run, as well as all the necessary input data files.  Without these you cannot really run the code.  Maybe we should add some explanations for new users who would like to try TIMES without a user shell...

**Comment by mbussieck** [comment]
@Antti-L thanks for the explanation. I was curious to find out what I can do with the TIMES that I get from github. Seeing your https://github.com/etsap-TIMES/TIMES_model/pull/2#issuecomment-576838722 it seems that github is used as a distribution channel for the TIME package that require not only a GAMS installation but data and a user shell. It would be really cool to have a small self-contained TIMES distribution that would even work with the GAMS demo (2k rows and 2k columns) or community license (5k rows and 5k columns).

**Comment by Antti-L** [comment]
@mbussieck  Yes, of course TIMES needs the user-specified model data for generating the model according to the specifications. But as I tried to explain, a user shell is _normally_ used, but not required.  Only reading the documentation and GAMS are required for being able to specify and run a model.

It would be easy to create a self-contained package containing TIMES, the model data for a small demo model, and the RUN file for running it with GAMS. If desired, I could create such if someone can point me to a suitable existing demo model.

**Comment by mbussieck** [comment]
I have been working with the Balmorel (http://www.balmorel.com) model before and they arranged the model (https://github.com/balmorelcommunity/Balmorel.git) and working data sets (https://github.com/balmorelcommunity/Balmorel_data.git) on github, so I could just do:

```
git clone https://github.com/balmorelcommunity/Balmorel.git
cd Balmorel/data
git clone https://github.com/balmorelcommunity/Balmorel_data.git
cd ../model
gams balmorel
```

Making some data sets (and what ever driver is necessary) avail in such a form for TIMES would be great. I would be happy to reduce a real data set (that exceeds the GAMS demo/community sizes) to one that fits such limits.

**Comment by Antti-L** [comment]
@mbussieck :
Thanks, we have been now discussing which kind of a Demo model would be suitable. One suggestion was to use the Demo12 model included in the ETSAP demo models, but although being very simple, it is still too big for the GAMS limits. Until we can decide about the suitable demo model(s) and where to upload them, you could try the attached, which is a self-containing **7zip** package with a reduced variant of the Demo12 model, which can be run by: **GAMS rundemo**.
[Demo12.zip](https://github.com/etsap-TIMES/TIMES_model/files/4112412/Demo12.zip)

**Comment by mbussieck** [comment]
@Antti-L, this is great. Thanks. I can get this to work now (on Windows). I think I remember some discussions with Gary Goldstein (?) that some TIMES users successfully migrated the TIMES source to Linux. Do you happen to know anything about this and where this stands?

**Comment by Antti-L** [comment]
@mbussieck  Good to know it worked.  Yes, TIMES has been tested and used on Linux as well, and it only has required small considerations mainly with some external "system calls", and case sensitivity of files and folders. It should remain standing as "working, but subject to possible minor issues". I omitted considering Linux with the demo package now, because 1) most TIMES users work on Win64 due to the user shells, and 2) I don't even have a Linux machine directly at my disposal to test it with. If you can try on Linux renaming the `Model` and `Source` subdirectories to all lower case and then the command:

`> gams demo12.run idir=../source ps=0 gdx=demo12 filecase=2`

while in the model subdirectory, maybe you can let me know if there are any problems with it, indicating that some small issues with the Linux compatibility may have crept in again?

**Comment by mbussieck** [comment]
@Antti-L, with your help I also got this to work under Linux. Thank you. While I have access to true Linux machines, I love to use my WSL (Windows Subsystem for Linux, see https://docs.microsoft.com/en-us/windows/wsl/install-win10) on my Window 10 desktop. 

I only had two minor issues:

1) My entire path needs to be lower case (I called the directory in which I placed model and source TIMES but it needs to be times). No problem.

2) I think line 53 in source/setglobs.gms requires an extra escape (\\) infront of the `$LOADR`:

```
$hiddencall sed "/\(^Scalar\|(\*)\)/{N;d;}; /^\([^$].*$\|$\)/d; s/\$LOAD.. /\$LOADR /" _dd_.dmp > _dd_.dd
```

**Comment by Antti-L** [comment]
@mbussieck : Many thanks.
On Windows the $ has the special meaning (end of line) only in the search string, not in the replacement string, and so escaping is not needed there (neither is it needed e.g. in Emacs regexp replacement strings). So, I am a bit surprised if it is required on Linux.

Does the Subsystem for Linux require having the Linux distribution for GAMS?

**Comment by mbussieck** [comment]
@Antti-L, yes WSL is just a regular Linux, so you need a native GAMS system for Linux (including a Linux license). We have generic licenses that work under Windows, Linux and Mac (they are slightly more expensive than single platform license). Please email support@gams.com (mention our discussion) and we arrange for such a license for you.

Yes, the `$hiddencall` calls the system shell (you also need this because you redirect (`>`). You could protect via single quotes, but then it does not work under Windows anymore...

**Comment by olejandro** [comment]
@Antti-L and @mbussieck, I've attempted to make larger TIMES model self-contained: https://github.com/energy-modelling-club/TIMES-DK_COMETS. For the moment, I did not specify any solver settings, except that CBC should be used, so it may take awhile to run :-).

**Comment by Antti-L** [comment]
Thank you Olex. 
I can see this model also has domain violations in (at least in tra_xtaxessubsidies.dd), due to the currency MKr18.  Is that intended, some leftover, or a modeling error?

**Comment by olejandro** [comment]
Yeah, I've noticed it, as well, along with the issues reported in the QA_log. :flushed: I'll check it out.

**Comment by Antti-L** [comment]
@olejandro Anyway, running the model scenarios appears to work well, and you have set it up quite nicely using a single RUN file picking up the relevant scenario input files.

**Comment by olejandro** [comment]
Thanks, @Antti-L :blush:

**Comment by mbussieck** [comment]
@olejandro I also got it to work on my machine. Thanks for making this available and pointing me to this. I think I am more than satisfied now and are happy closing this issue.
