### ISSUE TITLE
file SCREEN with filename CON

### ISSUE THREAD

**Issue by mbussieck** [etsap-TIMES/TIMES_model#3]
In `err_stat.mod` the file `SCREEN` uses file name `CON` to write to the console. I guess the intention on the SCREEN file is to write messages from TIMES to the GAMS log. This works okay on Windows with lo=1 (the current default). A much better way is to use the empty string as a file name (`FILE SCREEN / '' /;`). This works platform independent and writes to the GAMS log independent of if this goes to con or /dev/tty, stdout, or a log file.

**Comment by Antti-L** [comment]
Thanks for the comment.  Using CON here stems from the early days of TIMES.  Your suggestion of changing it will most likely be taken in the next versions.
